/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author JuanBernardoEstollos
 */
public class Forgot extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public Forgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(461, 318));
        setSize(new java.awt.Dimension(461, 318));
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 130, 16);

        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        getContentPane().add(juser);
        juser.setBounds(60, 50, 120, 22);

        Create.setText("Change password");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        getContentPane().add(Create);
        Create.setBounds(60, 230, 124, 20);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 230, 75, 23);

        jLabel4.setText("Enter backup code");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 20, 190, 30);

        jcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcodeActionPerformed(evt);
            }
        });
        getContentPane().add(jcode);
        jcode.setBounds(260, 50, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
  String newPassword = new String(juser.getPassword());
 String confirmPassword = new String(jcode.getPassword());
            
            if (newPassword.isEmpty()) {
                statusLabel.setText("Password cannot be empty");
                return;
            }
            
            if (!newPassword.equals(confirmPassword)) {
                statusLabel.setText("Passwords do not match");
                return;
            }
            
            boolean success = ClientService.updatePassword(username, newPassword);
            
            if (success) {
                JOptionPane.showMessageDialog(passwordDialog, 
                    "Password changed successfully", 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                passwordDialog.dispose();
                new Login().setVisible(true);
                dispose();
            } else {
                statusLabel.setText("Failed to update password");
            }
        
}

// Update the password change dialog's submit button action:
submitButton.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        String newPassword = new String(newPasswordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        
        if (newPassword.isEmpty()) {
            statusLabel.setText("Password cannot be empty");
            return;
        }
        
        if (!newPassword.equals(confirmPassword)) {
            statusLabel.setText("Passwords do not match");
            return;
        }
        
        boolean success = ClientService.updatePassword(username, newPassword);
        
        if (success) {
            JOptionPane.showMessageDialog(passwordDialog, 
                "Password changed successfully", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            passwordDialog.dispose();
            new Login().setVisible(true);
            dispose();
        } else {
            statusLabel.setText("Failed to update password");
        }
    
}

/**
 * Shows a dialog to change password
 */
private void showPasswordChangeDialog(final String username) {
    // Create a dialog for changing password
    final JDialog passwordDialog = new JDialog(this, "Change Password", true);
    passwordDialog.setLayout(new GridBagLayout());
    passwordDialog.setSize(350, 200);
    passwordDialog.setLocationRelativeTo(this);
    
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.insets = new Insets(5, 5, 5, 5);
    gbc.fill = GridBagConstraints.HORIZONTAL;
    
    // New password field
    gbc.gridx = 0;
    gbc.gridy = 0;
    passwordDialog.add(new JLabel("New Password:"), gbc);
    
    gbc.gridx = 1;
    gbc.gridy = 0;
    final JPasswordField newPasswordField = new JPasswordField(15);
    passwordDialog.add(newPasswordField, gbc);
    
    // Confirm password field
    gbc.gridx = 0;
    gbc.gridy = 1;
    passwordDialog.add(new JLabel("Confirm Password:"), gbc);
    
    gbc.gridx = 1;
    gbc.gridy = 1;
    final JPasswordField confirmPasswordField = new JPasswordField(15);
    passwordDialog.add(confirmPasswordField, gbc);
    
    // Status label
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    final JLabel statusLabel = new JLabel(" ");
    statusLabel.setForeground(Color.RED);
    passwordDialog.add(statusLabel, gbc);
    
    // Submit button
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.CENTER;
    JButton submitButton = new JButton("Change Password");
    submitButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Get new passwords
            String newPassword = new String(newPasswordField.getPassword());
            String confirmPassword = new String(confirmPasswordField.getPassword());
            
            // Validate passwords
            if (newPassword.isEmpty()) {
                statusLabel.setText("Password cannot be empty");
                return;
            }
            
            if (!newPassword.equals(confirmPassword)) {
                statusLabel.setText("Passwords do not match");
                return;
            }
            
            // Update password in database
            Connection conn = null;
            PreparedStatement stmt = null;
            
            try {
                // Connect to database
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_auth", "root", "");
                
                // Prepare update statement
                String updateQuery = "UPDATE users SET password = ? WHERE username = ?";
                stmt = conn.prepareStatement(updateQuery);
                stmt.setString(1, newPassword);
                stmt.setString(2, username);
                
                // Execute update
                int rowsAffected = stmt.executeUpdate();
                
                if (rowsAffected > 0) {
                    // Password updated successfully
                    JOptionPane.showMessageDialog(passwordDialog, 
                            "Password changed successfully", 
                            "Success", 
                            JOptionPane.INFORMATION_MESSAGE);
                    passwordDialog.dispose();
                } else {
                    statusLabel.setText("Failed to update password");
                }
            } catch (SQLException ex) {
                statusLabel.setText("Database error: " + ex.getMessage());
                ex.printStackTrace();
            } finally {
                try {
                    if (stmt != null) stmt.close();
                    if (conn != null) conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    });
    passwordDialog.add(submitButton, gbc);
    
    // Display the dialog
    passwordDialog.setVisible(true);

    }//GEN-LAST:event_CreateActionPerformed

    private void jcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
new Login().setVisible(true); 
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jcode;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
