/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finals;
import javax.swing.*;
import java.math.BigDecimal;
/**
 *
 * @author JuanBernardoEstollos
 */
public class Loan extends javax.swing.JFrame {
   
    
    /**
     * Creates new form Loan
     */
  public Loan(String username) {
        initComponents();
        jname.setText("Welcome, " + username);
        
        try {
            User user = ClientService.getUserDetails(username);
            if (user != null) {
                Balance.setText(user.getBalance().toString());
                Jcredit1.setText(user.getCredit().toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading user data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jname = new javax.swing.JTextField();
        credit = new javax.swing.JLabel();
        Balance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        credit1 = new javax.swing.JLabel();
        Jcredit1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(461, 318));
        setMinimumSize(new java.awt.Dimension(461, 318));
        setPreferredSize(new java.awt.Dimension(461, 318));
        setSize(new java.awt.Dimension(461, 318));
        getContentPane().setLayout(null);

        jname.setText("jTextField1");
        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });
        getContentPane().add(jname);
        jname.setBounds(50, 20, 150, 40);

        credit.setText("Remaining balance:");
        getContentPane().add(credit);
        credit.setBounds(200, 70, 110, 16);

        Balance.setText("jTextField1");
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });
        getContentPane().add(Balance);
        Balance.setBounds(310, 60, 150, 40);

        jButton1.setText("Get Loan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 230, 120, 50);

        jButton2.setText("Pay Loan");
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 230, 140, 50);

        credit1.setText("Credit:");
        getContentPane().add(credit1);
        credit1.setBounds(260, 20, 35, 16);

        Jcredit1.setText("jTextField1");
        Jcredit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcredit1ActionPerformed(evt);
            }
        });
        getContentPane().add(Jcredit1);
        Jcredit1.setBounds(310, 10, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceActionPerformed

    private void Jcredit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcredit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcredit1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Balance;
    private javax.swing.JTextField Jcredit1;
    private javax.swing.JLabel credit;
    private javax.swing.JLabel credit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jname;
    // End of variables declaration//GEN-END:variables

}

